MAX_EDGES <- 10000
MAX_CHANNELS <- 9
MAX_LAYERS <- 18
COLOR_BREWER_PALETTE <- 'Set3'
COLOR_BREWER_PALETTE_DARK <- 'Set1'
CHANNEL_COLORS_LIGHT <- brewer.pal(MAX_CHANNELS, COLOR_BREWER_PALETTE)
CHANNEL_COLORS_DARK <- brewer.pal(MAX_CHANNELS, COLOR_BREWER_PALETTE_DARK)
VR_DOWNSCALE_FACTOR <- 300
POST_REQUEST_PATH <- 'tmp/'
API_URL <- "https://bib.fleming.gr/bib/api/arena3dweb/vr/" # "http://localhost:8080/api/arena3dweb/vr/"
